# Tasks for installing and configuring RabbitMQ and custom plugins on the system


# Following guide from https://www.rabbitmq.com/docs/install-debian#apt-quick-start-cloudsmith

- name: Ensure tooling for install is present
  ansible.builtin.apt:
    name:
      - curl
      - gnupg
      - apt-transport-https
    state: present

- name: Add Team RabbitMQs main apt signing key
  ansible.builtin.shell:
    cmd: curl -1sLf "https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA" | sudo gpg --dearmor | sudo tee /usr/share/keyrings/com.rabbitmq.team.gpg > /dev/null

- name: Add Cloudsmith Erlang repo apt signing key
  ansible.builtin.shell:
    cmd: curl -1sLf https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key | sudo gpg --dearmor | sudo tee {{ rabbitmq_cloudsmith_erlang_signing_key_location }} > /dev/null

- name: Add Cloudsmith Rabbit repo apt signing key
  ansible.builtin.shell:
    cmd: curl -1sLf https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-server.9F4587F226208342.key | sudo gpg --dearmor | sudo tee {{ rabbitmq_cloudsmith_rabbit_signing_key_location }} > /dev/null

- name: Add RabbitMQ apt repos (erlang + rabbitmq-server cloudsmith repos) by adding sources.list
  ansible.builtin.template:
    src: rabbitmq.sources.list.j2
    dest: /etc/apt/sources.list.d/rabbitmq.list

# See https://stackoverflow.com/questions/32407164/the-vm-is-running-with-native-name-encoding-of-latin1-which-may-cause-elixir-to
- name: Make sure LC_ALL locale is set to UTF-8
  ansible.builtin.command:
    cmd: update-locale LC_ALL=en_US.UTF-8

- name: Get hostname for RabbitMQ instance at time of installation
  ansible.builtin.shell:
    cmd: "hostname"
  register: hostname_return

- name: Output collected hostname info
  ansible.builtin.debug:
    var: hostname_return.stdout

- name: Install rabbitmq-server package (from RabbitMQ repo)
  ansible.builtin.apt:
    update_cache: true
    name: rabbitmq-server
    state: present

- name: Start rabbitmq-server in order to use the rabbitctl command in next task
  ansible.builtin.service:
    name: rabbitmq-server
    state: started

- name: Get RabbitMQ plugins dir
  ansible.builtin.shell:
    cmd: rabbitmqctl environment | grep -A 1 plugins_dir | grep -oE '"/.+"' | cut -d ':' -f 2 | tr -d '"'
  register: rabbit_plugins_dir

- name: Output RabbitMQ plugins path
  ansible.builtin.debug:
    var: rabbit_plugins_dir.stdout

- name: Plugins to install, debug output
  ansible.builtin.debug:
    msg: "files/{{ item }}.ez -> {{ rabbit_plugins_dir.stdout }}"
  with_items: '{{ rabbitmq_custom_plugins }}'

- name: Place custom plugins into the plugins dir
  ansible.builtin.copy:
    src: "{{ item }}.ez"
    dest: "{{ rabbit_plugins_dir.stdout }}"
  with_items: '{{ rabbitmq_custom_plugins }}'

- name: Stop rabbitmq-server to add config file
  ansible.builtin.service:
    name: rabbitmq-server
    state: stopped

- name: Configure rabbitmq-server
  ansible.builtin.template:
    src: rabbitmq.conf.j2
    dest: /etc/rabbitmq/rabbitmq.conf

- name: Start rabbitmq-server to enable plugins and add users
  ansible.builtin.service:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: Enable custom plugins
  community.rabbitmq.rabbitmq_plugin:
    name: "{{ item }}"
    state: enabled
  with_items: '{{ rabbitmq_custom_plugins }}'

- name: Enable management plugin
  community.rabbitmq.rabbitmq_plugin:
    new_only: yes # keeps previously installed plugins
    name: rabbitmq_management
    state: enabled
  when: rabbitmq_manage

- name: Setup rabbitmq user with admin access (providing node name in FQDN/cluster mode)
  community.rabbitmq.rabbitmq_user:
    user: "{{ rabbitmq_default_user }}"
    password: "{{ rabbitmq_default_pass }}"
    vhost: "{{ rabbitmq_default_vhost }}"
    configure_priv: "{{ rabbitmq_configure_priv }}"
    read_priv: "{{ rabbitmq_read_priv }}"
    write_priv: "{{ rabbitmq_write_priv }}"
    tags: "{{ rabbitmq_default_user_tags }}"
    state: "{{ rabbitmq_user_state }}"
    node: "{{ rabbitmq_nodename }}@{{ hostname_return.stdout }}"
  when:
    - rabbitmq_create_user
    - rabbitmq_cluster_bootup_play

- name: Setup rabbitmq user with admin access (no node name, localhost mode)
  community.rabbitmq.rabbitmq_user:
    user: "{{ rabbitmq_default_user }}"
    password: "{{ rabbitmq_default_pass }}"
    vhost: "{{ rabbitmq_default_vhost }}"
    configure_priv: "{{ rabbitmq_configure_priv }}"
    read_priv: "{{ rabbitmq_read_priv }}"
    write_priv: "{{ rabbitmq_write_priv }}"
    tags: "{{ rabbitmq_default_user_tags|join(',') }}"
    state: "{{ rabbitmq_user_state }}"
  when:
    - rabbitmq_create_user
    - not rabbitmq_cluster_bootup_play
